<?php

namespace app\admin\controller;

use app\cigoadmin\controller\backend\SessionAuthCheck;
use app\cigoadmin\model\AuthRule;

class Index extends SessionAuthCheck
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->assign('title', '西谷后台');
        $this->assign('admin_module_name', 'Demo');
        return $this->fetch('cigoadmin@index/index');
    }


    public function getLeftMenuData()
    {
        $this->success('', '', $this->authLeftMenuDataList);
    }

    public function getTopMenuData()
    {
        $this->success('', '', $this->authTopMenuDataList);
    }

    public function addOptRate()
    {
        $model = new AuthRule();
        $menuData = $model->where([['id', 'in', $_POST['ids']]])->find();
        if ($menuData) {
            $model->where([['id', 'in', $_POST['ids']]])->setInc('opt_rate');
        }
    }
}
